# Generated by Django 4.1.2 on 2022-11-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Наименование категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('tilda_id', models.CharField(max_length=255, verbose_name='ID тильды')),
            ],
        ),
    ]
